### ISSUE TITLE
Show SVG as image for WinForm Button using the repo.

### ISSUE THREAD

**Issue by zydjohnHotmail** [managed-commons/SvgNet#37]
**Is your feature request related to a problem? Please describe.**
I want to use a SVG file to be used as image for WinForm button

**Describe the solution you'd like**
I want to use a SVG file to be used as image for WinForm button, just like other raster format images, like PNG, JPG, BMP.

**Describe alternatives you've considered**
Now I can use PNG, JPG, BMP format of images for Button image in WinForm C# program.

**Additional context**
Hello:
I am working on a WinForm App for C# in Windows 10.
I can use raster format picture as the image for a button, like PNG, JPG, BMP.
However, those images are big, some times size are in MB.  But for SVG, they are rather small, and for simple shapes, they are perfect.
But I can’t see any code example to use one SVG image for button image in a C# program.
Please show some code.
For example, I have one circle SVG file with a check:

<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-circle-check" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <circle cx="12" cy="12" r="9" />
  <path d="M9 12l2 2l4 -4" />
</svg>

Let’s say this file is called: “C:\Images\Circle1.svg”, and in my C# WinForm program, I created one Button called “button1”.
How I can use the Circle1.svg as the image for button1 in my C# program?
If not yet, then please add this feature!
Thanks,

**Comment by monoman** [comment]
Hi @zydjohnHotmail 

SVG is not a raster image format, it is a vector image format, that is why for more some images it is smaller than equivalent raster images specially for larger resolutions as it is resolution-independent (but sometimes it is the reverse for more complex images and lower resolutions)

**You won't be able to really avoid having a bitmap in memory, to keep responsiveness, to put and SVG inside a button but you can use SvgNet to draw your SVG into a bitmap created in memory for you to set in the button, and that bitmap can be sized as small as needed (like twice or four times the size of the button so that details can be really rendered and then smoothed when scaled down to fit he button).**

Look at our winforms test app code to see how to draw your SVG into a bitmap.

The other approach we use to evaluate how well we are rendering the SVG is to embed a webview (a browser) in the window and make it load the SVG, but that is truly overkill and hard to not mess with events to try to use inside buttons.

**Comment by monoman** [comment]
Later today I'll try to cook some example, if someone doesn't make it before me.

**Comment by zydjohnHotmail** [comment]
Thanks and wish to see your code.

**Comment by monoman** [comment]
Sorry, sometimes even I forget that SvgNet only deals with converting GDI primitives to SVG. We ourselves always need to use WebBrowser controls to render SVG, either loaded as the ones our API generate.

I suggest to try other libraries like [SVG](https://github.com/svg-net/SVG), their Sample SVGViewer shows how to load an svg into a Bitmap that you can set in the Image property of the button (or the BackgroundImage property)
