### ISSUE TITLE
In the 'Lines' visual test a 3 segment polyline is appearing as a 2-segment line

### ISSUE THREAD

**Issue by monoman** [managed-commons/SvgNet#47]
**Describe the bug**
![image](https://user-images.githubusercontent.com/237364/127860357-dd424623-1dd1-48ab-b2af-b8cc99bbfe8b.png)

**To Reproduce**
1. Run the SvgGdi test app
2. Select 'Lines' in the combobox
3. See error

**Expected behavior**
Same geometry.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: SvgNet.2.1.6

**Additional context**
Maybe it is unrelated but in the debug output appears: Exception thrown: 'System.ArgumentException' in System.Drawing.dll

**Comment by T1G0FF** [comment]
The angle on that SVG output looks like the 3rd point is halfway between the where the 3rd and 4th points are on the GDI. 
I'm unable to look at the code at the moment, but some poor image editing suggests it is:
![SVGNet_PolyLineBug](https://user-images.githubusercontent.com/866616/127970883-ac971225-5113-4ab2-8378-ab7c69961ffc.png)
That might help narrow down where the bug is occurring.

**Comment by monoman** [comment]
Thanks Thomas for helping with the diagnosys 👍 , I'll be looking into it
in the weekend
Rafael Teixeira
O..:.)oooo

**Comment by monoman** [comment]
Finally solved on v3.3.9 - The Metafile parsing hack is unreliable and not needed in the most cases, only really for custom line caps
