### ISSUE TITLE
Does not support drawing paths

### ISSUE THREAD

**Issue by i00** [managed-commons/SvgNet#8]
Wish it supported this.

**Comment by monoman** [comment]
**Would you care to elaborate about it?** 
Maybe someone could become interested in contributing it.
I really don't have the knowledge even to estimate the effort. :disappointed:

**Comment by glopesdev** [comment]
@monoman @allisterb Thanks for the work putting together this initial implementation. Unfortunately the current version does not handle straight-line segments correctly.

Instead of merging all the lines in the `GraphicsPath` inside a single SVG `path` element, it splits them into multiple `line` elements.

Because of this, corners are not handled correctly and lines seem to be broken. You can reproduce the problem easily simply by trying to draw a star or hexagon with the current implementation. Also combining a bezier followed by a straight-line segment does not work.

I will take a look at the current implementation, and if it is easy to understand, I might try to fix it. Anyway, for now I wanted to leave this report and confirm that this issue is still very much open until at least curves and straight-lines are handled correctly.

**Comment by monoman** [comment]
@glopesdev Thanks for the keep-alive, and, in advance, the hard work you will put forward to ameliorate the issue. 💯

**Comment by monoman** [comment]
Implemented and released on version 1.0.7
